"""Purposeful native-16 prop placements for Claudeville's north district."""

TARGET_BOUNDS = {
    "Home 1": (44, 8, 64, 33),
    "University": (74, 10, 98, 33),
    "Agent Academy": (110, 12, 128, 33),
    "Market": (148, 24, 160, 33),
    "Post Office": (150, 44, 170, 63),
}
TARGETS = frozenset(TARGET_BOUNDS)
REVISION = 4

# layer, left, top, right, bottom, gid
TILE_FILLS = (
    ("Interior Ground", 58, 13, 63, 20, 55219),  # Home 1 bathroom field.
    ("Exterior Ground", 48, 27, 64, 32, 1328),  # Home 1 garden patio.
)

# layer, visual x, visual y, gid. Complete the blocked bedroom partition.
TILE_EDITS = (
    ("Wall", 48, 20, 55536),
    ("Wall", 49, 20, 55651),
    ("Wall", 50, 20, 55651),
    ("Wall", 51, 20, 55651),
    ("Wall", 52, 20, 55651),
    ("Wall", 53, 20, 55651),
    ("Wall", 54, 20, 55651),
    ("Wall", 55, 20, 55541),
    ("Wall", 58, 20, 55536),
    ("Wall", 59, 20, 55651),
    ("Wall", 60, 20, 55651),
    ("Wall", 61, 20, 55541),
)

# sector, zone, semantic role, purpose cluster, stable asset key, visual x, visual y
PLACEMENTS = (
    # Home 1: a garden-focused household with complete domestic clusters.
    ("Home 1", "home_1.living_room", "storage", "north-wall storage", "prop.interiors_v3.living.0038", 47, 12),
    ("Home 1", "home_1.living_room", "common-room-table", "conversation sofa", "prop.interiors_v3.living.0003", 51, 15),
    ("Home 1", "home_1.living_room", "common-room-table", "conversation armchair", "prop.interiors_v3.living.0004", 54, 17),
    ("Home 1", "home_1.living_room", "common-room-table", "conversation coffee table", "prop.interiors_v3.living.0051", 51, 17),
    ("Home 1", "home_1.living_room", "common-room-table", "media wall", "prop.interiors_v3.living.0019", 55, 15),
    ("Home 1", "home_1.living_room", "plant", "garden household", "prop.interiors_v3.living.0013", 47, 18),
    ("Home 1", "home_1.living_room", "dining-table", "family dining", "prop.office.table_light", 51, 19),
    ("Home 1", "home_1.living_room", "dining-chair", "family dining", "prop.interiors_v3.classroom_library.0001", 49, 19),
    ("Home 1", "home_1.living_room", "dining-chair", "family dining", "prop.interiors_v3.classroom_library.0002", 53, 19),
    ("Home 1", "home_1.kitchen", "cooking-area", "cook line", "prop.interiors_v3.kitchen.0121", 55, 15),
    ("Home 1", "home_1.kitchen", "prep", "cook line", "prop.interiors_v3.kitchen.0126", 57, 15),
    ("Home 1", "home_1.kitchen", "refrigerator", "cold storage", "prop.interiors_v3.kitchen.0160", 55, 17),
    ("Home 1", "home_1.kitchen", "storage", "cook line", "prop.interiors_v3.kitchen.0195", 57, 18),
    ("Home 1", "home_1.bathroom", "shower", "washroom", "prop.interiors_v3.bathroom.0064", 59, 15),
    ("Home 1", "home_1.bathroom", "wash", "washroom", "prop.interiors_v3.bathroom.0151", 61, 15),
    ("Home 1", "home_1.bathroom", "toilet-fixture", "washroom", "prop.interiors_v3.bathroom.0021", 59, 18),
    ("Home 1", "home_1.bathroom", "storage", "washroom", "prop.interiors_v3.bathroom.0083", 61, 19),
    ("Home 1", "home_1.bedroom", "closet", "west storage", "prop.interiors_v3.bedroom.0004", 49, 21),
    ("Home 1", "home_1.bedroom", "bed", "sleep", "prop.interiors_v3.bedroom.0088", 53, 23),
    ("Home 1", "home_1.bedroom", "nightstand", "sleep", "prop.office.side_table", 55, 23),
    ("Home 1", "home_1.bedroom", "closet", "east storage", "prop.interiors_v3.bedroom.0386", 59, 23),
    ("Home 1", "home_1.bedroom", "desk", "garden planning", "prop.interiors_v3.bedroom.0263", 61, 23),
    ("Home 1", "home_1.bedroom", "desk-chair", "garden planning", "prop.interiors_v3.classroom_library.0002", 61, 25),
    ("Home 1", "home_1.garden", "garden-seat", "potting garden", "prop.garden.bench_horizontal", 49, 27),
    ("Home 1", "home_1.garden", "potting-display", "potting garden", "prop.interiors_v3.grocery.0371", 58, 30),
    ("Home 1", "home_1.garden", "flower-display", "potting garden", "prop.interiors_v3.grocery.0374", 61, 30),
    ("Home 1", "home_1.garden", "shade-tree", "potting garden", "prop.landscape.tree_07", 61, 29),
    ("Home 1", "home_1.garden", "mailbox", "front garden", "prop.street.mailbox", 47, 31),
    ("Home 1", "home_1.garden", "entrance", "front threshold", "prop.facade.residential_door_open", 53, 32),

    # University: lecture, research lab, service line, and two dining groups.
    ("University", "university.lecture", "lecture-board", "teaching wall", "prop.interiors_v3.classroom_library.0036", 80, 12),
    ("University", "university.lecture", "instructor-desk", "teaching wall", "prop.interiors_v3.classroom_library.0025", 80, 14),
    ("University", "university.lecture", "lecture-seating", "row A", "prop.interiors_v3.classroom_library.0015", 77, 15),
    ("University", "university.lecture", "lecture-seating", "row A", "prop.interiors_v3.classroom_library.0016", 83, 15),
    ("University", "university.lecture", "lecture-seating", "row B", "prop.interiors_v3.classroom_library.0017", 77, 19),
    ("University", "university.lecture", "lecture-seating", "row B", "prop.interiors_v3.classroom_library.0018", 83, 19),
    ("University", "university.lecture", "globe", "teaching wall", "prop.interiors_v3.classroom_library.0034", 85, 14),
    ("University", "university.lecture", "reference-shelf", "west wall", "prop.interiors_v3.classroom_library.0043", 75, 19),
    ("University", "university.study_lab", "reference-shelf", "north wall", "prop.interiors_v3.classroom_library.0055", 89, 13),
    ("University", "university.study_lab", "reference-shelf", "north wall", "prop.interiors_v3.classroom_library.0058", 95, 13),
    ("University", "university.study_lab", "computer-station", "west workstation", "prop.office.computer_desk", 89, 15),
    ("University", "university.study_lab", "computer-station", "east workstation", "prop.office.computer_desk", 95, 15),
    ("University", "university.study_lab", "study-chair", "west workstation", "prop.interiors_v3.classroom_library.0002", 89, 17),
    ("University", "university.study_lab", "study-chair", "east workstation", "prop.interiors_v3.classroom_library.0004", 95, 17),
    ("University", "university.study_lab", "reference-table", "south research station", "prop.interiors_v3.classroom_library.0015", 89, 20),
    ("University", "university.study_lab", "reference-table", "south research station", "prop.interiors_v3.classroom_library.0016", 95, 20),
    ("University", "university.study_lab", "printer", "south research station", "prop.office.printer_station", 96, 22),
    ("University", "university.cafeteria", "prep", "back counter", "prop.interiors_v3.kitchen.0126", 85, 23),
    ("University", "university.cafeteria", "coffee-service", "back counter", "prop.office.coffee_station", 89, 23),
    ("University", "university.cafeteria", "refrigerator", "back counter", "prop.interiors_v3.kitchen.0160", 91, 23),
    ("University", "university.cafeteria", "service-counter", "service line", "prop.office.counter_cream_left", 87, 25),
    ("University", "university.cafeteria", "service-counter", "service line", "prop.office.counter_cream_middle", 89, 25),
    ("University", "university.cafeteria", "service-counter", "service line", "prop.office.counter_cream_right", 91, 25),
    ("University", "university.cafeteria", "food-display", "service line", "prop.interiors_v3.ice_cream.0020", 87, 24),
    ("University", "university.cafeteria", "food-display", "service line", "prop.interiors_v3.ice_cream.0023", 90, 24),
    ("University", "university.cafeteria", "vending", "self service", "prop.office.vending_machine", 83, 27),
    ("University", "university.cafeteria", "dining-table", "west table", "prop.office.table_walnut", 85, 29),
    ("University", "university.cafeteria", "dining-table", "east table", "prop.office.table_light", 91, 29),
    ("University", "university.cafeteria", "dining-chair", "west table", "prop.interiors_v3.classroom_library.0001", 84, 31),
    ("University", "university.cafeteria", "dining-chair", "west table", "prop.interiors_v3.classroom_library.0002", 86, 31),
    ("University", "university.cafeteria", "dining-chair", "east table", "prop.interiors_v3.classroom_library.0003", 90, 31),
    ("University", "university.cafeteria", "dining-chair", "east table", "prop.interiors_v3.classroom_library.0004", 92, 31),
    ("University", "university.cafeteria", "waste-bin", "tray return", "prop.office.waste_bin", 92, 27),
    ("University", "university.cafeteria", "entrance", "front threshold", "prop.facade.door_open", 85, 32),

    # Agent Academy: applied simulator training, classroom, reception, and lounge.
    ("Agent Academy", "academy.training_lab", "simulator-monitor", "west simulator", "prop.interiors_v3.shooting_range.0011", 113, 13),
    ("Agent Academy", "academy.training_lab", "simulator-monitor", "east simulator", "prop.interiors_v3.shooting_range.0012", 117, 13),
    ("Agent Academy", "academy.training_lab", "training-simulator", "west simulator", "prop.office.training_station", 113, 15),
    ("Agent Academy", "academy.training_lab", "training-simulator", "east simulator", "prop.office.training_station", 117, 15),
    ("Agent Academy", "academy.training_lab", "target-trainer", "practical training", "prop.interiors_v3.shooting_range.0015", 113, 21),
    ("Agent Academy", "academy.training_lab", "fitness-trainer", "practical training", "prop.interiors_v3.gym.0176", 117, 21),
    ("Agent Academy", "academy.training_lab", "training-mat", "training circuit", "prop.interiors_v3.gym.0196", 115, 20),
    ("Agent Academy", "academy.training_lab", "equipment-storage", "training circuit", "prop.interiors_v3.gym.0166", 115, 19),
    ("Agent Academy", "academy.training_lab", "training-chart", "debrief wall", "prop.office.wall_chart", 119, 13),
    ("Agent Academy", "academy.classroom", "class-board", "teaching wall", "prop.interiors_v3.classroom_library.0036", 124, 13),
    ("Agent Academy", "academy.classroom", "instructor-desk", "teaching wall", "prop.interiors_v3.classroom_library.0025", 124, 15),
    ("Agent Academy", "academy.classroom", "classroom-seating", "row A", "prop.interiors_v3.classroom_library.0015", 122, 17),
    ("Agent Academy", "academy.classroom", "classroom-seating", "row A", "prop.interiors_v3.classroom_library.0016", 126, 17),
    ("Agent Academy", "academy.classroom", "classroom-seating", "row B", "prop.interiors_v3.classroom_library.0017", 122, 21),
    ("Agent Academy", "academy.classroom", "classroom-seating", "row B", "prop.interiors_v3.classroom_library.0018", 126, 21),
    ("Agent Academy", "academy.classroom", "reference-shelf", "classroom support", "prop.interiors_v3.classroom_library.0043", 121, 23),
    ("Agent Academy", "academy.classroom", "reference-shelf", "classroom support", "prop.interiors_v3.classroom_library.0045", 127, 23),
    ("Agent Academy", "academy.reception", "academy-map", "information wall", "prop.office.town_map", 111, 27),
    ("Agent Academy", "academy.reception", "notice-board", "information wall", "prop.office.notice_board", 115, 27),
    ("Agent Academy", "academy.reception", "reception-desk", "front desk", "prop.office.counter_walnut_left", 111, 29),
    ("Agent Academy", "academy.reception", "reception-desk", "front desk", "prop.office.counter_walnut_middle", 113, 29),
    ("Agent Academy", "academy.reception", "reception-desk", "front desk", "prop.office.counter_walnut_right", 115, 29),
    ("Agent Academy", "academy.reception", "terminal", "front desk", "prop.office.monitor_blue", 113, 28),
    ("Agent Academy", "academy.reception", "entrance", "front threshold", "prop.facade.door_open", 113, 32),
    ("Agent Academy", "academy.lounge", "coffee-service", "lounge refreshment", "prop.office.coffee_station", 125, 27),
    ("Agent Academy", "academy.lounge", "lounge-rug", "conversation", "prop.interiors_v3.gym.0197", 121, 29),
    ("Agent Academy", "academy.lounge", "lounge-seating", "conversation", "prop.office.armchair_mustard", 119, 29),
    ("Agent Academy", "academy.lounge", "lounge-seating", "conversation", "prop.office.sofa_dark", 123, 29),
    ("Agent Academy", "academy.lounge", "side-table", "conversation", "prop.office.side_table", 121, 31),
    ("Agent Academy", "academy.lounge", "lounge-table", "conversation", "prop.interiors_v3.living.0065", 121, 29),
    ("Agent Academy", "academy.lounge", "water-cooler", "lounge refreshment", "prop.office.water_cooler", 125, 31),
    ("Agent Academy", "academy.lounge", "plant", "lounge refreshment", "prop.interiors_v3.living.0016", 125, 31),

    # Market: a dense stock wall and a complete checkout/customer-tool cluster.
    ("Market", "market.retail", "stock-display", "chilled wall", "prop.interiors_v3.grocery.0058", 151, 27),
    ("Market", "market.retail", "stock-display", "chilled wall", "prop.interiors_v3.grocery.0060", 153, 27),
    ("Market", "market.retail", "stock-display", "chilled wall", "prop.interiors_v3.grocery.0062", 155, 27),
    ("Market", "market.retail", "stock-display", "dry-goods wall", "prop.interiors_v3.grocery.0099", 157, 27),
    ("Market", "market.retail", "stock-display", "dry-goods wall", "prop.interiors_v3.grocery.0101", 159, 27),
    ("Market", "market.checkout", "checkout-counter", "checkout", "prop.interiors_v3.grocery.0158", 151, 29),
    ("Market", "market.checkout", "checkout-counter", "checkout", "prop.interiors_v3.grocery.0177", 153, 29),
    ("Market", "market.checkout", "basket-stack", "customer tools", "prop.interiors_v3.grocery.0249", 157, 29),
    ("Market", "market.checkout", "shopping-cart", "customer tools", "prop.interiors_v3.grocery.0251", 159, 31),
    ("Market", "market.retail", "produce-island", "fresh produce", "prop.interiors_v3.grocery.0203", 157, 30),
    ("Market", "market.checkout", "entrance", "front threshold", "prop.facade.door_open", 155, 32),

    # Post Office: public service, continuous counter, sorting wall, and waiting.
    ("Post Office", "post.service", "service-notice", "postal information", "prop.office.notice_board", 153, 47),
    ("Post Office", "post.service", "rate-board", "postal information", "prop.office.town_map", 157, 47),
    ("Post Office", "post.service", "records", "clerk support", "prop.office.filing_cabinet", 151, 49),
    ("Post Office", "post.service", "postal-terminal", "west clerk", "prop.office.cash_register", 153, 50),
    ("Post Office", "post.service", "postal-terminal", "east clerk", "prop.office.cash_register", 157, 50),
    ("Post Office", "post.service", "clerk-chair", "west clerk", "prop.office.chair_blue", 153, 51),
    ("Post Office", "post.service", "clerk-chair", "east clerk", "prop.office.chair_orange", 157, 51),
    ("Post Office", "post.service", "printer", "clerk support", "prop.office.printer_station", 159, 50),
    ("Post Office", "post.service", "postal-counter", "service line", "prop.office.counter_cream_left", 151, 53),
    ("Post Office", "post.service", "postal-counter", "service line", "prop.office.counter_cream_middle", 153, 53),
    ("Post Office", "post.service", "postal-counter", "service line", "prop.office.counter_cream_middle", 155, 53),
    ("Post Office", "post.service", "postal-counter", "service line", "prop.office.counter_cream_right", 157, 53),
    ("Post Office", "post.service", "postal-counter", "service line", "prop.office.counter_cream_middle", 159, 53),
    ("Post Office", "post.sorting", "parcel-sorting-rack", "continuous cubby wall", "prop.interiors_v3.classroom_library.0067", 163, 49),
    ("Post Office", "post.sorting", "parcel-sorting-rack", "continuous cubby wall", "prop.interiors_v3.classroom_library.0069", 166, 49),
    ("Post Office", "post.sorting", "parcel-sorting-rack", "continuous cubby wall", "prop.interiors_v3.classroom_library.0071", 169, 49),
    ("Post Office", "post.sorting", "parcel", "continuous cubby wall", "prop.post.package_stack", 165, 51),
    ("Post Office", "post.sorting", "parcel", "continuous cubby wall", "prop.post.package_large", 168, 51),
    ("Post Office", "post.sorting", "sorting-station", "label workstation", "prop.office.computer_desk", 169, 53),
    ("Post Office", "post.sorting", "sorting-station", "label workstation", "prop.office.printer_station", 169, 55),
    ("Post Office", "post.sorting", "sorting-station", "copy station", "prop.office.copier", 167, 57),
    ("Post Office", "post.sorting", "mail-sorting-table", "west sorting table", "prop.office.table_light", 165, 59),
    ("Post Office", "post.sorting", "mail-sorting-table", "east sorting table", "prop.office.table_light", 169, 59),
    ("Post Office", "post.sorting", "packing-bench", "west packing bench", "prop.office.table_walnut_medium", 164, 55),
    ("Post Office", "post.sorting", "parcel", "west packing bench", "prop.post.package_small", 163, 54),
    ("Post Office", "post.sorting", "packing-bench", "east packing bench", "prop.office.table_walnut_medium", 168, 57),
    ("Post Office", "post.sorting", "parcel", "east packing bench", "prop.post.package_stack", 167, 56),
    ("Post Office", "post.sorting", "sorted-mail", "west sorting table", "prop.office.paper_stack", 163, 57),
    ("Post Office", "post.sorting", "sorted-mail", "east sorting table", "prop.office.paper_stack", 169, 57),
    ("Post Office", "post.sorting", "waste-bin", "sorting support", "prop.office.waste_bin", 169, 61),
    ("Post Office", "post.waiting", "queue-runner", "service queue", "prop.interiors_v3.gym.0196", 154, 56),
    ("Post Office", "post.waiting", "waiting-seating", "wall-backed waiting bay", "prop.interiors_v3.living.0003", 153, 59),
    ("Post Office", "post.waiting", "side-table", "wall-backed waiting bay", "prop.office.side_table", 156, 59),
    ("Post Office", "post.waiting", "parcel-preparation-table", "packing station", "prop.office.table_light", 158, 59),
    ("Post Office", "post.waiting", "packing-forms", "packing station", "prop.office.paper_stack", 158, 58),
    ("Post Office", "post.waiting", "parcel", "packing station", "prop.post.package_small", 159, 59),
    ("Post Office", "post.waiting", "water-cooler", "waiting support", "prop.office.water_cooler", 151, 61),
    ("Post Office", "post.waiting", "entrance", "front threshold", "prop.facade.door_open", 161, 62),
)
